#!/usr/bin/env node
/**
 * Builds cloudflare/worker.js with the phone UI embedded (correct text/html).
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const htmlPath = path.join(root, 'cloudflare', 'public', 'index.html');
const outPath = path.join(root, 'cloudflare', 'worker.js');

if (!fs.existsSync(htmlPath)) {
  console.error('Missing cloudflare/public/index.html — run npm run build:phone first');
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf8');
const worker = `/**
 * AUTO-GENERATED by scripts/build-worker.js — do not edit by hand.
 * Serves the phone UI + Cursor API CORS proxy.
 */
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
  'Access-Control-Allow-Headers': 'Authorization, Content-Type, Accept, x-cursor-path, x-cursor-method',
  'Access-Control-Max-Age': '86400'
};

const APP_HTML = ${JSON.stringify(html)};

function json(status, obj) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json; charset=utf-8' }
  });
}

async function proxyCursor(request, url) {
  const auth = request.headers.get('Authorization') || '';
  if (!auth) {
    return json(401, { error: 'Missing Authorization header (Cursor API key)' });
  }

  const apiPath =
    request.headers.get('x-cursor-path') ||
    url.searchParams.get('path') ||
    '/v1/models';
  if (!String(apiPath).startsWith('/v1/')) {
    return json(400, { error: 'path must start with /v1/' });
  }

  const method = (
    request.headers.get('x-cursor-method') ||
    'GET'
  ).toUpperCase();

  // Drain body even for GET (phone always POSTs to this Worker)
  const incoming = await request.text();
  const target = 'https://api.cursor.com' + apiPath;

  try {
    const upstream = await fetch(target, {
      method,
      headers: {
        Authorization: auth,
        'Content-Type': 'application/json',
        Accept: 'application/json'
      },
      body: method === 'GET' || method === 'HEAD' ? undefined : incoming || undefined
    });
    const text = await upstream.text();
    return new Response(text, {
      status: upstream.status,
      headers: {
        ...CORS,
        'Content-Type': upstream.headers.get('content-type') || 'application/json'
      }
    });
  } catch (err) {
    return json(502, { error: err.message || 'Proxy failed' });
  }
}

export default {
  async fetch(request) {
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS });
    }

    const url = new URL(request.url);
    const pathName = url.pathname.replace(/\\/+$/, '') || '/';
    const wantsProxy =
      request.headers.has('x-cursor-path') || url.searchParams.has('path');

    if (request.method === 'GET' && pathName === '/health') {
      return json(200, {
        ok: true,
        service: 'cwayclient-cf-proxy',
        app: '/',
        routes: ['/', '/health', 'proxy via x-cursor-path → api.cursor.com']
      });
    }

    if (wantsProxy) {
      return proxyCursor(request, url);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      return new Response(request.method === 'HEAD' ? null : APP_HTML, {
        status: 200,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'no-store'
        }
      });
    }

    return json(405, { error: 'Method not allowed' });
  }
};
`;

fs.writeFileSync(outPath, worker);
console.log('Wrote', outPath, '(' + worker.length + ' bytes)');
