#!/usr/bin/env node
/**
 * Builds cloudflare/worker.js with the phone UI embedded (correct text/html).
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const htmlPath = path.join(root, 'cloudflare', 'public', 'index.html');
const outPath = path.join(root, 'cloudflare', 'worker.js');

if (!fs.existsSync(htmlPath)) {
  console.error('Missing cloudflare/public/index.html — run npm run build:phone first');
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf8');
const worker = `/**
 * AUTO-GENERATED by scripts/build-worker.js — do not edit by hand.
 * Phone UI + fast Workers AI chat + Cursor API proxy + ElevenLabs TTS/STT.
 */
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
  'Access-Control-Allow-Headers':
    'Authorization, Content-Type, Accept, x-cursor-path, x-cursor-method, x-elevenlabs-key',
  'Access-Control-Max-Age': '86400'
};

const APP_HTML = ${JSON.stringify(html)};
const DEFAULT_VOICE = 'EXAVITQu4vr4xnSDxMaL';

const SYSTEM_PROMPT = [
  'You are CwayClient, the central AI assistant of a personal operating system, similar to JARVIS.',
  'You coordinate modules, understand user intent, and decide which capability should be used. Never invent functionality.',
  '',
  'Core behaviour: be intelligent, calm, concise, and proactive. Think before acting. If multiple modules could solve a task, pick the most suitable. If a module cannot complete a task, say why — never pretend it succeeded.',
  '',
  'Modules and their current status on this device:',
  '- Conversation (LIVE): questions, explanations, session context, clarifying questions.',
  '- Voice (LIVE): the user talks via the mic; your replies are spoken aloud. Keep answers voice-friendly.',
  '- Memory (LIVE): the app has a Memory screen; anything the user saved there is provided to you below as "Saved memories". Use them naturally. If the user asks you to remember something new, tell them to save it on the Memory screen (or that you will keep it in mind for this session).',
  '- Task Manager (LIVE, LOCAL): the app has a Tasks screen with checklists and priorities. You cannot add tasks yourself yet — point the user to the Tasks screen or the floating orb.',
  '- Notes (LIVE, LOCAL): the app has a Notes screen. Same rule: you cannot write notes yourself yet.',
  '- Calendar, Search, Files, Automation, Device Control, Notifications, Music, Email, Vision (NOT CONNECTED YET): if asked, explain the module is not wired up yet, and offer what you CAN do instead (draft the text, plan the steps, remember it for this session).',
  '',
  'Decision making: understand intent, pick the module, gather info, act, verify, respond clearly.',
  'Error handling: explain limitations, suggest alternatives, never fabricate success, ask when information is missing.',
  '',
  'Personality: professional, helpful, efficient, friendly, confident, never arrogant.',
  'Output style: spoken replies — 1 to 3 short sentences for simple things, a few more only when truly needed. Plain text only: no markdown, no bullet lists, no code blocks, no emojis.'
].join('\\n');

function json(status, obj) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json; charset=utf-8' }
  });
}

async function proxyCursor(request, url) {
  const auth = request.headers.get('Authorization') || '';
  if (!auth) {
    return json(401, { error: 'Missing Authorization header (Cursor API key)' });
  }

  const apiPath =
    request.headers.get('x-cursor-path') ||
    url.searchParams.get('path') ||
    '/v1/models';
  if (!String(apiPath).startsWith('/v1/')) {
    return json(400, { error: 'path must start with /v1/' });
  }

  const method = (request.headers.get('x-cursor-method') || 'GET').toUpperCase();
  const incoming = await request.text();
  const target = 'https://api.cursor.com' + apiPath;

  try {
    const upstream = await fetch(target, {
      method,
      headers: {
        Authorization: auth,
        'Content-Type': 'application/json',
        Accept: 'application/json'
      },
      body: method === 'GET' || method === 'HEAD' ? undefined : incoming || undefined
    });
    const text = await upstream.text();
    return new Response(text, {
      status: upstream.status,
      headers: {
        ...CORS,
        'Content-Type': upstream.headers.get('content-type') || 'application/json'
      }
    });
  } catch (err) {
    return json(502, { error: err.message || 'Proxy failed' });
  }
}

function elevenKey(request) {
  return (
    request.headers.get('x-elevenlabs-key') ||
    (request.headers.get('Authorization') || '').replace(/^Bearer\\s+/i, '')
  );
}

async function proxyElevenLabsTts(request) {
  const key = elevenKey(request);
  if (!key) {
    return json(401, { error: 'Missing ElevenLabs API key (x-elevenlabs-key)' });
  }

  let payload = {};
  try {
    payload = await request.json();
  } catch {
    return json(400, { error: 'Invalid JSON body' });
  }

  const text = String(payload.text || '').trim();
  if (!text) return json(400, { error: 'text is required' });

  const voiceId = String(payload.voiceId || DEFAULT_VOICE).trim() || DEFAULT_VOICE;
  const modelId = String(payload.modelId || 'eleven_turbo_v2_5').trim();

  try {
    const upstream = await fetch(
      'https://api.elevenlabs.io/v1/text-to-speech/' + encodeURIComponent(voiceId),
      {
        method: 'POST',
        headers: {
          'xi-api-key': key,
          'Content-Type': 'application/json',
          Accept: 'audio/mpeg'
        },
        body: JSON.stringify({
          text: text.slice(0, 4500),
          model_id: modelId,
          voice_settings: {
            stability: 0.4,
            similarity_boost: 0.75
          }
        })
      }
    );

    if (!upstream.ok) {
      const errText = await upstream.text();
      let message = errText.slice(0, 240);
      try {
        const parsed = JSON.parse(errText);
        message = parsed.detail?.message || parsed.message || message;
      } catch {
        /* keep */
      }
      return json(upstream.status, { error: message || 'ElevenLabs failed' });
    }

    return new Response(upstream.body, {
      status: 200,
      headers: {
        ...CORS,
        'Content-Type': 'audio/mpeg'
      }
    });
  } catch (err) {
    return json(502, { error: err.message || 'ElevenLabs proxy failed' });
  }
}

async function fastChat(request, env) {
  if (!env || !env.AI) {
    return json(503, { error: 'Workers AI not available on this deploy' });
  }

  let payload = {};
  try {
    payload = await request.json();
  } catch {
    return json(400, { error: 'Invalid JSON body' });
  }

  const incoming = Array.isArray(payload.messages) ? payload.messages : [];
  const memory = String(payload.memory || '').slice(0, 1200).trim();
  const systemContent = memory
    ? SYSTEM_PROMPT + '\\n\\nSaved memories the user asked you to keep (from the Memory screen): ' + memory
    : SYSTEM_PROMPT;
  const messages = [
    { role: 'system', content: systemContent },
    ...incoming
      .filter((m) => m && (m.role === 'user' || m.role === 'assistant') && m.content)
      .slice(-8)
      .map((m) => ({ role: m.role, content: String(m.content).slice(0, 1500) }))
  ];

  const wantStream = payload.stream === true;
  const opts = { messages, max_tokens: 220, temperature: 0.6 };
  // -fast runs on speculative-decoding hardware: same weights, much lower latency.
  const MODELS = ['@cf/meta/llama-3.1-8b-instruct-fast', '@cf/meta/llama-3.1-8b-instruct'];

  let lastErr = null;
  for (const model of MODELS) {
    try {
      if (wantStream) {
        const stream = await env.AI.run(model, { ...opts, stream: true });
        return new Response(stream, {
          headers: {
            ...CORS,
            'Content-Type': 'text/event-stream; charset=utf-8',
            'Cache-Control': 'no-store'
          }
        });
      }
      const result = await env.AI.run(model, opts);
      const text = String(result?.response || result?.result || result?.text || '').trim();
      if (!text) throw new Error('Empty AI response');
      return json(200, { ok: true, text, provider: 'workers-ai', model });
    } catch (err) {
      lastErr = err;
    }
  }
  return json(502, { error: (lastErr && lastErr.message) || 'Workers AI failed' });
}

async function proxyElevenLabsStt(request) {
  const key = elevenKey(request);
  if (!key) {
    return json(401, { error: 'Missing ElevenLabs API key (x-elevenlabs-key)' });
  }

  let form;
  try {
    form = await request.formData();
  } catch {
    return json(400, { error: 'Expected multipart form data with file' });
  }

  const file = form.get('file');
  if (!file) return json(400, { error: 'file is required' });

  const upstreamForm = new FormData();
  upstreamForm.append('file', file, file.name || 'cway-audio.m4a');
  upstreamForm.append('model_id', String(form.get('model_id') || 'scribe_v1'));
  const language = form.get('language_code');
  if (language) upstreamForm.append('language_code', String(language));

  try {
    const upstream = await fetch('https://api.elevenlabs.io/v1/speech-to-text', {
      method: 'POST',
      headers: { 'xi-api-key': key },
      body: upstreamForm
    });
    const text = await upstream.text();
    return new Response(text, {
      status: upstream.status,
      headers: {
        ...CORS,
        'Content-Type': upstream.headers.get('content-type') || 'application/json'
      }
    });
  } catch (err) {
    return json(502, { error: err.message || 'ElevenLabs STT proxy failed' });
  }
}

export default {
  async fetch(request, env) {
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS });
    }

    const url = new URL(request.url);
    const pathName = url.pathname.replace(/\\/+$/, '') || '/';
    const wantsProxy =
      request.headers.has('x-cursor-path') || url.searchParams.has('path');

    if (request.method === 'GET' && pathName === '/health') {
      return json(200, {
        ok: true,
        service: 'cwayclient-cf-proxy',
        app: '/',
        ai: Boolean(env && env.AI),
        routes: ['/', '/health', '/chat', '/tts', '/stt', 'cursor proxy via x-cursor-path']
      });
    }

    if (request.method === 'POST' && pathName === '/chat') {
      return fastChat(request, env);
    }

    if (request.method === 'POST' && pathName === '/tts') {
      return proxyElevenLabsTts(request);
    }

    if (request.method === 'POST' && pathName === '/stt') {
      return proxyElevenLabsStt(request);
    }

    if (wantsProxy) {
      return proxyCursor(request, url);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      return new Response(request.method === 'HEAD' ? null : APP_HTML, {
        status: 200,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'no-store'
        }
      });
    }

    return json(405, { error: 'Method not allowed' });
  }
};
`;

fs.writeFileSync(outPath, worker);
console.log('Wrote', outPath, '(' + worker.length + ' bytes)');
