#!/usr/bin/env node
/**
 * Builds cloudflare/worker.js with the phone UI embedded (correct text/html).
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const htmlPath = path.join(root, 'cloudflare', 'public', 'index.html');
const outPath = path.join(root, 'cloudflare', 'worker.js');

if (!fs.existsSync(htmlPath)) {
  console.error('Missing cloudflare/public/index.html — run npm run build:phone first');
  process.exit(1);
}

const html = fs.readFileSync(htmlPath, 'utf8');
const worker = `/**
 * AUTO-GENERATED by scripts/build-worker.js — do not edit by hand.
 * Phone UI + Cursor API proxy + ElevenLabs TTS/STT proxy.
 */
const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET,POST,OPTIONS',
  'Access-Control-Allow-Headers':
    'Authorization, Content-Type, Accept, x-cursor-path, x-cursor-method, x-elevenlabs-key',
  'Access-Control-Max-Age': '86400'
};

const APP_HTML = ${JSON.stringify(html)};
const DEFAULT_VOICE = '21m00Tcm4TlvDq8ikWAM';

function json(status, obj) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: { ...CORS, 'Content-Type': 'application/json; charset=utf-8' }
  });
}

async function proxyCursor(request, url) {
  const auth = request.headers.get('Authorization') || '';
  if (!auth) {
    return json(401, { error: 'Missing Authorization header (Cursor API key)' });
  }

  const apiPath =
    request.headers.get('x-cursor-path') ||
    url.searchParams.get('path') ||
    '/v1/models';
  if (!String(apiPath).startsWith('/v1/')) {
    return json(400, { error: 'path must start with /v1/' });
  }

  const method = (request.headers.get('x-cursor-method') || 'GET').toUpperCase();
  const incoming = await request.text();
  const target = 'https://api.cursor.com' + apiPath;

  try {
    const upstream = await fetch(target, {
      method,
      headers: {
        Authorization: auth,
        'Content-Type': 'application/json',
        Accept: 'application/json'
      },
      body: method === 'GET' || method === 'HEAD' ? undefined : incoming || undefined
    });
    const text = await upstream.text();
    return new Response(text, {
      status: upstream.status,
      headers: {
        ...CORS,
        'Content-Type': upstream.headers.get('content-type') || 'application/json'
      }
    });
  } catch (err) {
    return json(502, { error: err.message || 'Proxy failed' });
  }
}

function elevenKey(request) {
  return (
    request.headers.get('x-elevenlabs-key') ||
    (request.headers.get('Authorization') || '').replace(/^Bearer\\s+/i, '')
  );
}

async function proxyElevenLabsTts(request) {
  const key = elevenKey(request);
  if (!key) {
    return json(401, { error: 'Missing ElevenLabs API key (x-elevenlabs-key)' });
  }

  let payload = {};
  try {
    payload = await request.json();
  } catch {
    return json(400, { error: 'Invalid JSON body' });
  }

  const text = String(payload.text || '').trim();
  if (!text) return json(400, { error: 'text is required' });

  const voiceId = String(payload.voiceId || DEFAULT_VOICE).trim() || DEFAULT_VOICE;
  const modelId = String(payload.modelId || 'eleven_turbo_v2_5').trim();

  try {
    const upstream = await fetch(
      'https://api.elevenlabs.io/v1/text-to-speech/' + encodeURIComponent(voiceId),
      {
        method: 'POST',
        headers: {
          'xi-api-key': key,
          'Content-Type': 'application/json',
          Accept: 'audio/mpeg'
        },
        body: JSON.stringify({
          text: text.slice(0, 4500),
          model_id: modelId,
          voice_settings: {
            stability: 0.4,
            similarity_boost: 0.75
          }
        })
      }
    );

    if (!upstream.ok) {
      const errText = await upstream.text();
      let message = errText.slice(0, 240);
      try {
        const parsed = JSON.parse(errText);
        message = parsed.detail?.message || parsed.message || message;
      } catch {
        /* keep */
      }
      return json(upstream.status, { error: message || 'ElevenLabs failed' });
    }

    return new Response(upstream.body, {
      status: 200,
      headers: {
        ...CORS,
        'Content-Type': 'audio/mpeg'
      }
    });
  } catch (err) {
    return json(502, { error: err.message || 'ElevenLabs proxy failed' });
  }
}

async function proxyElevenLabsStt(request) {
  const key = elevenKey(request);
  if (!key) {
    return json(401, { error: 'Missing ElevenLabs API key (x-elevenlabs-key)' });
  }

  let form;
  try {
    form = await request.formData();
  } catch {
    return json(400, { error: 'Expected multipart form data with file' });
  }

  const file = form.get('file');
  if (!file) return json(400, { error: 'file is required' });

  const upstreamForm = new FormData();
  upstreamForm.append('file', file, file.name || 'cway-audio.m4a');
  upstreamForm.append('model_id', String(form.get('model_id') || 'scribe_v1'));
  const language = form.get('language_code');
  if (language) upstreamForm.append('language_code', String(language));

  try {
    const upstream = await fetch('https://api.elevenlabs.io/v1/speech-to-text', {
      method: 'POST',
      headers: { 'xi-api-key': key },
      body: upstreamForm
    });
    const text = await upstream.text();
    return new Response(text, {
      status: upstream.status,
      headers: {
        ...CORS,
        'Content-Type': upstream.headers.get('content-type') || 'application/json'
      }
    });
  } catch (err) {
    return json(502, { error: err.message || 'ElevenLabs STT proxy failed' });
  }
}

export default {
  async fetch(request) {
    if (request.method === 'OPTIONS') {
      return new Response(null, { status: 204, headers: CORS });
    }

    const url = new URL(request.url);
    const pathName = url.pathname.replace(/\\/+$/, '') || '/';
    const wantsProxy =
      request.headers.has('x-cursor-path') || url.searchParams.has('path');

    if (request.method === 'GET' && pathName === '/health') {
      return json(200, {
        ok: true,
        service: 'cwayclient-cf-proxy',
        app: '/',
        routes: ['/', '/health', '/tts', '/stt', 'cursor proxy via x-cursor-path']
      });
    }

    if (request.method === 'POST' && pathName === '/tts') {
      return proxyElevenLabsTts(request);
    }

    if (request.method === 'POST' && pathName === '/stt') {
      return proxyElevenLabsStt(request);
    }

    if (wantsProxy) {
      return proxyCursor(request, url);
    }

    if (request.method === 'GET' || request.method === 'HEAD') {
      return new Response(request.method === 'HEAD' ? null : APP_HTML, {
        status: 200,
        headers: {
          'Content-Type': 'text/html; charset=utf-8',
          'Cache-Control': 'no-store'
        }
      });
    }

    return json(405, { error: 'Method not allowed' });
  }
};
`;

fs.writeFileSync(outPath, worker);
console.log('Wrote', outPath, '(' + worker.length + ' bytes)');
